version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq-container
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - user-movie-net
    restart: always
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

  mysql-service:
    image: mysql:latest
    ports:
      - "3306:3306"
    container_name: mysql-container
    networks:
      - user-movie-net
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  mongodb-service:
    image: mongo:latest
    container_name: mongo-container
    networks:
      - user-movie-net
    ports:
      - "27017:27017"

  userauthenticationservice:
    container_name: user-authentication-service
    build: userAuthentication/
    networks:
      - user-movie-net
    ports:
      - "8080:8080"
    depends_on:
      - mysql-service
    restart: always

  recommendation:
    container_name: recommendation-service
    build: recommendation/
    networks:
      - user-movie-net
    ports:
      - "8081:8081"
    depends_on:
      - mongodb-service
    restart: always
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq-container

  usermovieservice:
    container_name: movie-container
    build: movieService/
    networks:
      - user-movie-net
    ports:
      - "8082:8082"
    depends_on:
      - mongodb-service
    restart: always

  favmovieservice:
    container_name: favourite-movie-service
    build: favouriteMovie/
    networks:
      - user-movie-net
    ports:
      - "8083:8083"
    depends_on:
      - mongodb-service
    restart: always
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq-container

  apigateway:
    container_name: api-gateway
    build: ApiGateway/
    networks:
      - user-movie-net
    ports:
      - "9000:9000"

  eureka-service:
    container_name: eureka-service
    build: eurekaServer/
    restart: always
    networks:
      - user-movie-net
    ports:
      - "8761:8761"
networks:
  user-movie-net:
    driver: bridge








